# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa67ec2af48e4404f665adbc6a87cc612a37650e484cd1bda33ca110e6d4e089ad2b0dc85687c6aa27dfe237e7068ea1f9ab04199fb8a0614dfb1941675611b9

test:
  secret_key_base: 05661cc7ee2f76b908f187b62349e6df08487e1687ae2870f01ea524b88c2f599b71933ab30d31ca2be3892bbc06c137997801bac36021525ad4ceed310f8386

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
